### ISSUE TITLE
Protocol method or API for passing data to peers on instantiation

### ISSUE THREAD

**Issue by scriptjs** [mafintosh/hypercore-protocol#12]
I found the previous extension useful. It is no longer supported in 6.x.  Each extension provided an emitter so I could trigger a method on peers following the handshake. The use case I was using it for was to send it a list of hypercore keys, then allowing each peer to determine whether it had a complete set.

This worked in 5.x
```
  let stream = protocol()

  stream.on('handshake', () => {
    let channel = stream.open(feed.key)
    channel.on('sendKeys', (receivedKeys)  => {
       // Do something
    })
    channel.sendKeys(JSON.stringify(keys))
  })
  
```
I can't seem yet to find a way to use the existing api to get anything equivalent. What do you think of being able to pass and optional object when instantiating a channel and being able to retrieve it on the feed ie.

```
  let stream = protocol()

  stream.on('handshake', () => {
    let channel = stream.feed(feed.key, { keys: new Buffer(keys) })
    channel.on('feed', (message) => {
      // Do something
    })

```

**Comment by mafintosh** [comment]
Oh yea the extension api is getting readded soon. It was only cut to get 5 out the door

**Comment by scriptjs** [comment]
Thanks! Quite keen to be working with the latest hypercore. Quite thrilled with the new hypercore :) Looking forward to gaining back the capability in protocol that existed in 5.x

**Comment by mafintosh** [comment]
The extension api will be a bit simpler in 6. Something like this probably:

``` js
stream.on('handshake', function () {
  channel.on('extension:send-json', function (data) {
  })
  channel.extension('send-json', JSON.stringify('hello'))
})
```

**Comment by mafintosh** [comment]
Also, to answer your original question support an opaque `userdata` buffer as part of the handshake is a good idea actually. Feel free to send a PR for that if you wanna help out :)

**Comment by scriptjs** [comment]
@mafintosh On the opaque userdata, I was reading the code yesterday and would like to help. Was first attempting to understand the code changes from 5 to 6. I should be useful soon, just getting up to speed then I will attempt some changes. Thank you for encouraging these changes!

**Comment by mafintosh** [comment]
It should be as easy as adding it to the handshake protobuf message and
then accepting it in the constructor

**Comment by scriptjs** [comment]
Yup, will do it.
