### ISSUE TITLE
Error:  sodium.crypto_stream_xor_instance is not a function

### ISSUE THREAD

**Issue by siuying** [mafintosh/hypercore-protocol#15]
When running hypercore=6.2.4 (hypercore-protocol=6.3.1) + browserify + Chrome

> bundle.js:5770 Uncaught TypeError: sodium.crypto_stream_xor_instance is not a function
>    at Protocol.feed (bundle.js:5770)

**Comment by mafintosh** [comment]
you can get around this for now by doing {encrypt: false} in the replicate function. browser transports are usually encrypted anyway

**Comment by siuying** [comment]
Thanks for the pointer! ``feed.replicate({encrypt: false})`` work for me.

**Comment by blahah** [comment]
@mafintosh I'm getting this in sciencefair on old macOS which is falling back to sodium js. Is there an easy way to pass that encrypt option through the hyperdrive?

**Comment by mafintosh** [comment]
@blahah ah, we forgot to add this one to the js. let me add it.

**Comment by blahah** [comment]
Fixed in sodium-javascript: https://github.com/sodium-friends/sodium-javascript/issues/5
