### ISSUE TITLE
Document ack

### ISSUE THREAD

**Issue by scriptjs** [mafintosh/hypercore-protocol#20]
ack was recently added but lacks documentation.

@emilbayes Would be great if you could update the README.md with the API and usage.

**Comment by emilbayes** [comment]
Made a PR now. I figured the more filling docs would live in https://github.com/mafintosh/hypercore itself

**Comment by scriptjs** [comment]
Super, thanks. Sure, I realize the features of hypercore-protocol are typically consumed by hypercore, hyperdrive and friends.
