### ISSUE TITLE
extensions should be sorted on protocol creation

### ISSUE THREAD

**Issue by bplaster** [mafintosh/hypercore-protocol#27]
Currently, when handshaking with a peer, the `extensions` indices are defined using the `indexOf` function from `sorted-indexof`. This requires the arrays to already be sorted, so if you pass in an unsorted array into `opts.extensions`, the extensions are not matched. It would be helpful to either document this or just sort the array when it's passed in. Thanks!

**Comment by madelinecameron** [comment]
https://github.com/mafintosh/hypercore-protocol/pull/23 ;)

**Comment by bplaster** [comment]
Ah! Nice! Thanks @madelinecameron and @pfrazee !

**Comment by mafintosh** [comment]
fixed in master
