### ISSUE TITLE
Use standard symmetric Diffie-Hellman calculation in Noise handshake

### ISSUE THREAD

**Issue by Frando** [mafintosh/hypercore-protocol#51]
Hypercore uses [noise-protocol](https://github.com/emilbayes/noise-protocol) for handshaking, which currently uses the asymmetric `sodium_crypto_kx` API for the Diffie-Hellman part of the handshake. This differs from other Noise framework implementations and the Noise recommendations, which makes it harder to implement hypercore-protocol in other languages [like Rust](https://github.com/Frando/hypercore-protocol-rust-experiments). @emilbayes already wrote the patch for noise-protocol to [use a standard, symmetric DH](https://github.com/emilbayes/noise-protocol/tree/standard-dh). He also wants to add a patch to use the more common ChaChaPoly cipher instead of the currently used XChaChaPoly cipher (this was much easier to add to a Rust implementation of Noise than the DH part would be though). See also [this issue in datrs](https://github.com/datrs/hypercore/issues/92) for details.

To ease cross-language implementation I propose to switch to the standard DH rather sooner than later (i.e. before a wider Dat 2 release) because it's a wire-protocol breaking change.

The actual change would just be raising a version number of noise-protocol in simple-hypercore-protocol. I'm opening this issue for potential discussion and documentation.

**Comment by mafintosh** [comment]
Good catch, tracking this with @emilbayes

**Comment by RangerMauve** [comment]
Would this change the crypto problems we're having in the browser?

**Comment by emilbayes** [comment]
@RangerMauve Not exactly but a step in the right direction

**Comment by Frando** [comment]
Hei @mafintosh, @emilbayes, what is your current thinking on this issue - can this be switched soonish/before a wider Dat2 release or are there things holding it back?

It's a wire protocol breaking change so i would say it would make sense to plan this a bit ahead of time with a notice for people to chime in and a rough date/release on when it will happen

**Comment by okdistribute** [comment]
Can we add this to agenda Wednesday for discussion?

**Comment by mafintosh** [comment]
@Frando ya we'll resolve that before the wider release

**Comment by okdistribute** [comment]
@mafintosh thanks for responding. Do you have any rough idea regarding a potential timeline? We're planning on rolling out internet sync sometime in the next few months in Mapeo, and breaking changes like this make it more difficult for partners who don't have quick internet access to download a new version of the app (but would be fast enough to send a MB of raw data).

**Comment by mafintosh** [comment]
Within the next weeks

**Comment by okdistribute** [comment]
Thanks maf!

**Comment by mafintosh** [comment]
Plan is to land this before the hyperdrive release next week together with another breaking change so we can be stable going forward

**Comment by mafintosh** [comment]
The other change is a slight change in signing to make strong links easier

**Comment by mafintosh** [comment]
Fixed in Hypercore v9 and latest version of this module
